apiVersion: v1
kind: Service
metadata:
  name: cpn-service
  labels:
    app: cpn
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: cpn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpn-deployment
  labels:
    app: cpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpn
  template:
    metadata:
      labels:
        app: cpn
    spec:
      containers:
      - name: cpn
        image: ghcr.io/georgepetri/cpn:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
