apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - casapetri.ro
    secretName: tls
  rules:
    - host: casapetri.ro
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
             service:
              name: cpn-service
              port:
                number: 80