apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpn-deployment
  labels:
    app: cpn
spec:
  # todo change replicas
  replicas: 1
  selector:
    matchLabels:
      app: cpn
  template:
    metadata:
      labels:
        app: cpn
    spec:
      containers:
      - name: cpn
        image: ghcr.io/georgepetri/cpn:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cpn-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000  
  selector:
    app: cpn